spring:
  application:
    name: scheduled-payments-services
  profiles:
    active: "dev"
server:
  port: 8080
springdoc:

  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: false
artifact:
  groupId: '@project.groupId@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'  